metadata:
  # https://github.com/ioos/ioosngdac/wiki/NGDAC-NetCDF-File-Format-Version-2
  acknowledgement: Funding from Schmitt Sciences, OBVI, West African Margin project
  comment:        "Southern Benguela Upwelling System glider deployment
                   from 19 Nov to 21 Jan 2026."
  contributor_name: Sarah Nicholson, Isabelle Giddy, Estel Font, Nikita Qosholo, Vusani Mikosi, STS
  contributor_role: Principal Investigator,Senior Research, Postdoc, PhD, PhD, Technicians
  creator_email: isgiddy@gmail.com
  creator_name:  Isabelle Giddy
  creator_url: ''
  # R: real time. P: provisional
  data_mode: 'P'
  # date_created etc: added automatically
  # numbers must be eenclosed by strings so YAML keeps as strings
  deployment_id: '1'
  deployment_name: 'wam_sbus_test'
  deployment_start: '2025-11-19'
  deployment_end: '2026-01-21'
  format_version: IOOS_Glider_NetCDF_v2.0.nc
  # id filled automatically...
  glider_name: socco-461
  glider_serial: '461'
  glider_model: Slocum G2 
  glider_instrument_name: slocum
  glider_wmo: "999999"
  institution: SOCCO-CSIR
  keywords: "AUVS, Autonomous Underwater Vehicles, Oceans, Ocean Pressure,
             Water Pressure, Oceans, Ocean Temperature, Water Temperature,
             Oceans, Salinity/Density, Conductivity, Oceans,
             Salinity/Density, Density, Oceans, Salinity/Density, Salinity, Oxygen, Nitrogen"
  keywords_vocabulary: GCMD Science Keywords
  license: "tbd"
  metadata_link: ""
  Metadata_Conventions: CF-1.8, Unidata Dataset Discovery v1.0
  naming_authority: "ca.uvic.cproof"
  platform_type:    "Slocum Glider"
  processing_level: "Data provided as is with no expressed or implied
                     assurance of quality assurance or quality control."
  project: West African Margin
  project_url: '' 
  publisher_email: sarahanne.n@gmail.com
  publisher_name:  Sarah Nicholson
  publisher_url: ''
  references:     cproof toolbox URL
  # https://www.nodc.noaa.gov/General/NODC-Archive/seanamelist.txt
  sea_name:   Benguela Current, South Atlantic Ocean
  source:     Observational data from a profiling glider.
  standard_name_vocabulary: CF STandard Name Table v72
  summary: First leg of the Southern Benguela Upwelling System glider deployment from 19 Nov to 21 Jan 2026.
  transmission_system: IRRIDIUM
  wmo_id: "999999"


glider_devices:
  pressure:
    make: Micron
    model: Pressure
    serial: '96645'
  ctd:
    make: Seabird
    model: SlocumCTD
    serial: '9171'
    long_name: Seabird SlocumCTD
    make_model: Seabird SlocumCTD
    factory_calibrated: " "
    calibration_date: "22 Aug 2019 "
    calibration_report: " "
    comment:   " "
  optics:
    make: Wetlabs
    model: BB2FLSLC
    serial: '1193'
    calibration_date: "30 July 2019"
  # par:
  #   make: Biospherical Instruments Inc.
  #   model: QSP2155
  #   serial: '50182'
  #   calibration_date: "24 March 2014"
  oxygen:
    make: AADI
    model: Optode4831
    serial: '1206'
    calibration_date: "10 September 2019"



# map between glider variables and netcdf variables.  This shouldn't
# change too much.
netcdf_variables:
  # Time and Place:
  time:
    source:   sci_m_present_time
    long_name:     Time
    standard_name: time
    calendar:      gregorian
    units:         seconds since 1970-01-01T00:00:00Z
    axis:          T
    observation_type: "measured"

  time_ctd:
    source:   sci_ctd41cp_timestamp
    long_name:     Time measured by ctd
    standard_name: time measured by ctd
    calendar:      gregorian
    units:         seconds since 1970-01-01T00:00:00Z
    axis:          T
    observation_type: "measured"

  latitude:
    source:  m_lat
    long_name:    latitude
    standard_name: latitude
    units:        degrees_north
    axis:         Y
    comment:     "Estimated between surface fixes (dead-reckoning+GPS)"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    90.0
    valid_min:    -90.0
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326

  longitude:
    source:  m_lon
    long_name:    longitude
    standard_name: longitude
    units:        degrees_east
    axis:         X
    comment:     "Estimated between surface fixes (dead-reckoning+GPS)"
    observation_type: measured
    platform:     platform
    reference:    WGS84
    valid_max:    180.0
    valid_min:    -180.0
    coordinate_reference_frame:  urn:ogc:crs:EPSG::4326


  ## add a bunch of additional gps fixes
  lon_gps:
    source:  m_gps_lon
    comment:  "GPS"

  lat_gps:
    source:  m_gps_lat
    comment:  "GPS"

  inv_lat:
    source: m_gps_invalid_lat

  inv_lon:
    source: m_gps_invalid_lon

  far_lat:
    source: m_gps_toofar_lat

  far_lon:
    source: m_gps_toofar_lon

  ign_lat: 
    source: m_gps_ignored_lat
  
  ign_lon:
    source: m_gps_ignored_lon

  heading:
    source:  m_heading
    long_name:    glider heading angle
    standard_name: platform_orientation
    units:        degrees

  pitch:
    source:  m_pitch
    long_name:    glider pitch angle
    standard_name: platform_pitch_angle
    units:        degrees

  roll:
    source:  m_roll
    long_name:    glider roll angle
    standard_name: platform_roll_angle
    units:        degrees

  fin:
      source:  m_fin
      long_name:    glider fin angle
      standard_name: platform_fin_angle
      units:        degrees

  thruster_power:
      source:  m_thruster_power
      long_name:    glider thruster power
      standard_name: platform_thruster_power
      units:        Watts
  
  oil_volume:
      source:  m_de_oil_vol
      long_name:    measured oil volume in bladder
      standard_name: measured oil volume
      units:        mL

  # profile info:
  waypoint_latitude:
    source:  c_wpt_lat
    long_name:    waypoint latitude
    standard_name: latitude
    units:        degree_north

  waypoint_longitude:
    source:  c_wpt_lon
    long_name:    waypoint longitude
    standard_name: longitude
    units:        degree_east

  # data parameters
  conductivity:
    source:  sci_water_cond
    long_name:    water conductivity
    standard_name: sea_water_electrical_conductivity
    units:        mS cm-1
    instrument:    instrument_ctd
    valid_min:    0.
    valid_max:    10.
    observation_type: "measured"
    accuracy:      0.0003
    precision:     0.0001
    resolution:     0.00002

  temperature:
    source:  sci_water_temp
    long_name:    water temperature
    standard_name: sea_water_temperature
    units:        Celsius
    instrument:   instrument_ctd
    valid_min:    -5.0
    valid_max:    50.0
    observation_type: "measured"
    accuracy:      0.002
    precision:     0.001
    resolution:    0.0002

  pressure:
    source:  sci_water_pressure
    long_name:    water pressure
    standard_name:  sea_water_pressure
    units:        dbar
    conversion:   bar2dbar
    valid_min:    0.0
    valid_max:    2000.0
    positive:      "down"
    reference_datum:  "sea-surface"
    instrument:     "instrument_ctd"
    observation_type: "measured"
    accuracy:         1.0
    precision:        2.0
    resolution:       0.02
    comment:          "ctd pressure sensor"


# optics:
  chlorophyll:
    source:  sci_bb2flsv8_chl_sig
    long_name:    chlorophyll
    standard_name: concentration_of_chlorophyll_in_sea_water
    units:        mg m-3

  # cdom:
  #   source:  sci_flbbcd_cdom_units
  #   long_name:    CDOM
  #   units:        ppb

  backscatter_470:
    source:  sci_bb2flsv8_b470_sig
    long_name:    470 nm wavelength backscatter
    units:         "1"

  backscatter_700:
    source:  sci_bb2flsv8_b700_sig
    long_name:    700 nm wavelength backscatter
    units:         "1"

# PAR
  # par:
  #   source:  sci_bsipar_par 
  #   long_name:    photosynthetically available radiation
  #   standard_name: downwelling_photosynthetic_photon_flux_in_sea_water
  #   units:        umol m-2 s-1

# Oxygen
  oxygen_concentration:
    source:  sci_oxy4_oxygen  
    long_name:    oxygen concentration
    standard_name: mole_concentration_of_dissolved_molecular_oxygen_in_sea_water
    units:        umol l-1
  
  oxygen_temperature:
    source:  sci_oxy4_temp  
    long_name:    temperature measured by oxygen sensor
    standard_name: temperature measured by oxygen sensor
    units:        Celsius

  oxygen_timestamp:
    source:  sci_oxy4_timestamp  
    long_name:    time measured by oxygen sensor
    standard_name:    time measured by oxygen sensor
    calendar:      gregorian
    units:      seconds since 1970-01-01T00:00:00Z


# derived water speed:
  # water_velocity_eastward:
  #   source:    m_final_water_vx
  #   long_name:      mean eastward water velocity in segment
  #   standard_name:  barotropic_eastward_sea_water_velocity
  #   units:          m s-1
  #   coordinates:   time depth latitude longitude
  #
  # water_velocity_northward:
  #   source:    m_final_water_vy
  #   long_name:      mean northward water velocity in segment
  #   standard_name:  barotropic_northward_sea_water_velocity
  #   units:          m s-1
  #   coordinates:   time depth latitude longitude

profile_variables:
  # variables for extract_L1timeseries_profiles processing step...
  profile_id:
    comment: Sequential profile number within the trajectory.  This value is unique in each file that is part of a single trajectory/deployment.
    long_name: 'Profile ID'
    valid_max: 2147483646
    valid_min: 1

  profile_time:
    comment:           Timestamp corresponding to the mid-point of the profile
    long_name:         Profile Center Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time

  profile_time_start:
    comment:           Timestamp corresponding to the start of the profile
    long_name:         Profile Start Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time

  profile_time_end:
    comment:           Timestamp corresponding to the end of the profile
    long_name:         Profile End Time
    observation_type:  calculated
    platform:          platform
    standard_name:     time

  profile_lat:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Latitude
    observation_type:  calculated
    platform:          platform
    standard_name:     latitude
    units:             degrees_north
    valid_max:         90.0
    valid_min:         -90.0

  profile_lon:
    comment:           Value is interpolated to provide an estimate of the latitude at the mid-point of the profile
    long_name:         Profile Center Longitude
    observation_type:  calculated
    platform:          platform
    standard_name:     longitude
    units:             degrees_east
    valid_max:         180.0
    valid_min:         -180.0

  u:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Eastward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     eastward_sea_water_velocity
    units:             m s-1
    valid_max:         10.0
    valid_min:         -10.0

  v:
    comment:  The depth-averaged current is an estimate of the net current measured while the glider is underwater.  The value is calculated over the entire underwater segment, which may consist of 1 or more dives.
    long_name:         Depth-Averaged Northward Sea Water Velocity
    observation_type:  calculated
    platform:          platform
    standard_name:     northward_sea_water_velocity
    units:             m s-1
    valid_max:         10.0
    valid_min:         -10.0

  lon_uv:
    comment:           Not computed
    long_name:         Longitude
    observation_type:  calculated
    platform:          platform
    standard_name:     longitude
    units:             degrees_east
    valid_max:         180.0
    valid_min:         -180.0

  lat_uv:
    comment:           Not computed
    long_name:         Latitude
    observation_type:  calculated
    platform:          platform
    standard_name:     latitude
    units:             degrees_north
    valid_max:         90.0
    valid_min:         -90.0

  time_uv:
    comment:       Not computed
    long_name:     Time
    standard_name: time
    calendar:      gregorian
    units:         seconds since 1970-01-01T00:00:00Z
    observation_type: calculated

  instrument_ctd:
    comment:    pumped CTD
    calibration_date:     "30 Aug 2019"
    calibration_report:   " "
    factory_calibrated:  "yes"
    long_name:           Seabird Glider Payload CTD
    make_model:          Seabird GPCTD
    platform:            platform
    serial_number:       "9171"
    type:                platform