name: gliderwork
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - backports.zstd=1.3.0
  - bitarray=3.8.0
  - bitstring=4.3.1
  - blosc=1.21.6
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cftime=1.6.5
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.14.2
  - cycler=0.12.1
  - dask-core=2025.12.0
  - debugpy=1.8.19
  - decorator=5.2.1
  - executing=2.2.1
  - fonttools=4.61.1
  - freetype=2.14.1
  - fsspec=2026.1.0
  - gsw=3.6.20
  - h2=4.3.0
  - hdf4=4.2.15
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.3
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libsodium=1.0.20
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - locket=1.0.0
  - lz4-c=1.10.0
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.4
  - numpy=2.4.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - partd=1.4.2
  - pexpect=4.9.0
  - pillow=12.1.0
  - pip=25.3
  - platformdirs=4.5.1
  - polars=1.37.1
  - polars-runtime-32=1.37.1
  - pooch=1.8.2
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyglider=0.0.7
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - python=3.14.2
  - python-dateutil=2.9.0.post0
  - python-gil=3.14.2
  - python-tzdata=2025.3
  - python_abi=3.14
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - scipy=1.17.0
  - six=1.17.0
  - snappy=1.2.2
  - stack_data=0.6.3
  - tk=8.6.13
  - toolz=1.1.0
  - tornado=6.5.4
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - unicodedata2=17.0.0
  - urllib3=2.6.3
  - wcwidth=0.2.14
  - xarray=2025.12.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
      - dbdreader==0.5.8
      - iniconfig==2.3.0
      - lz4==4.4.5
      - pluggy==1.6.0
      - pytest==9.0.2
prefix: /Users/xnunei/miniconda3/envs/gliderwork
